baseURL = 'https://graceana.dev/'
languageCode = 'es-es'
title = 'Graceana dev'
theme = 'PaperMod'
contentDir = "content"

[params]
  math = true  # Activador global de matemÃ¡ticas
  enableKatex = true

[params.homeInfoParams]
  Title = "Â¡Hola, soy Ana PÃ©rez! ðŸ‘‹"
  Content = "En este espacio comparto mis aprendizajes, como referencia personal y para quienes puedan encontrarles utilidad"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ana-p%C3%A9rez-816834110/"

# --- CONFIGURACIÃ“N DE FORMATO (AquÃ­ estaba el truco) ---
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"

  # Esto permite que el signo $ pase sin romperse
  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      block = [['$$', '$$'], ['\\[', '\\]']]
      inline = [['$', '$'], ['\\(', '\\)']]

[taxonomies]
  category = "categories"
  tag = "tags"